services:
  # Backend Spring Boot
  - type: web
    name: recibo-backend
    env: docker
    dockerfilePath: ./Dockerfile
    region: oregon
    plan: free
    envVars:
      - key: SPRING_MAIL_USERNAME
        value: ludgalvao09@gmail.com
      - key: SPRING_MAIL_PASSWORD
        value: hfqb fhnt rsit mwsd
      - key: APP_EMAIL_REMETENTE
        value: ludgalvao09@gmail.com
      - key: APP_EMAIL_NOME_REMETENTE
        value: Sistema de Recibos - Precisao
      - key: APP_BACKEND_URL
        value: https://precisao-recibo.onrender.com
      - key: JAVA_TOOL_OPTIONS
        value: "-Xmx512m -Xms256m"
    healthCheckPath: /recibos


